In [13]:
import pandas as pd

# Import population estimates as a data frame.
df = pd.read_csv("Unemployment/Unemployment Med HH Inc -Table 1.csv", skiprows=7)

In [14]:
# Preview the data frame.
df.head()

,FIPStxt,State,Area_name,Rural_urban_continuum_code_2003,Urban_influence_code_2003,Rural_urban_continuum_code_2013,Urban_influence_code_2013,Civilian_labor_force_2007,Employed_2007,Unemployed_2007,...,Civilian_labor_force_2014,Employed_2014,Unemployed_2014,Unemployment_rate_2014,Civilian_labor_force_2015,Employed_2015,Unemployed_2015,Unemployment_rate_2015,Median_Household_Income_2015,Med_HH_Income_Percent_of_State_Total_2015
0,1000,AL,Alabama,,,,,"2,175,612","2,089,127","86,485",...,"2,161,313","2,014,284","147,029",6.8,"2,146,157","2,015,189","130,968",6.1,"$44,833",100.0
1,1001,AL,"Autauga County, AL",2,2,2,2,"24,383","23,577",806,...,"25,597","24,097","1,500",5.9,"25,308","23,981","1,327",5.2,"$56,580",126.2
2,1003,AL,"Baldwin County, AL",4,5,3,2,"82,659","80,099","2,560",...,"86,400","81,084","5,316",6.2,"87,316","82,525","4,791",5.5,"$52,387",116.8
3,1005,AL,"Barbour County, AL",6,6,6,6,"10,334","9,684",650,...,"8,849","7,913",936,10.6,"8,625","7,854",771,8.9,"$31,433",70.1
4,1007,AL,"Bibb County, AL",1,1,1,1,"8,791","8,432",359,...,"8,560","7,942",618,7.2,"8,490","7,929",561,6.6,"$40,767",90.9

In [35]:
# Check type of FIPStxt
type(df['FIPStxt'][0])

numpy.int64

In [37]:
# We only want the rows corresponding to states themselves, which all have multiples of 1000 as FIPS.
# Run a filter to check if the FIPStxt%1000 is 0 on preview.
df.head(100).loc[df['FIPStxt']%1000 == 0]

,FIPStxt,State,Area_name,Rural_urban_continuum_code_2003,Urban_influence_code_2003,Rural_urban_continuum_code_2013,Urban_influence_code_2013,Civilian_labor_force_2007,Employed_2007,Unemployed_2007,...,Civilian_labor_force_2014,Employed_2014,Unemployed_2014,Unemployment_rate_2014,Civilian_labor_force_2015,Employed_2015,Unemployed_2015,Unemployment_rate_2015,Median_Household_Income_2015,Med_HH_Income_Percent_of_State_Total_2015
0,1000,AL,Alabama,,,,,"2,175,612","2,089,127","86,485",...,"2,161,313","2,014,284","147,029",6.8,"2,146,157","2,015,189","130,968",6.1,"$44,833",100.0
68,2000,AK,Alaska,,,,,"350,785","328,579","22,206",...,"365,890","340,804","25,086",6.9,"363,822","340,227","23,595",6.5,"$73,391",100.0

In [40]:
# Run the same filter on the full data frame.
states = df.loc[df['FIPStxt']%1000 == 0]

In [41]:
# This is pretty close, but we also included Puerto Rico
states

,FIPStxt,State,Area_name,Rural_urban_continuum_code_2003,Urban_influence_code_2003,Rural_urban_continuum_code_2013,Urban_influence_code_2013,Civilian_labor_force_2007,Employed_2007,Unemployed_2007,...,Civilian_labor_force_2014,Employed_2014,Unemployed_2014,Unemployment_rate_2014,Civilian_labor_force_2015,Employed_2015,Unemployed_2015,Unemployment_rate_2015,Median_Household_Income_2015,Med_HH_Income_Percent_of_State_Total_2015
0,1000,AL,Alabama,,,,,"2,175,612","2,089,127","86,485",...,"2,161,313","2,014,284","147,029",6.8,"2,146,157","2,015,189","130,968",6.1,"$44,833",100.0
68,2000,AK,Alaska,,,,,"350,785","328,579","22,206",...,"365,890","340,804","25,086",6.9,"363,822","340,227","23,595",6.5,"$73,391",100.0
101,4000,AZ,Arizona,,,,,"3,034,016","2,917,117","116,899",...,"3,097,112","2,886,412","210,700",6.8,"3,152,708","2,959,518","193,190",6.1,"$51,473",100.0
117,5000,AR,Arkansas,,,,,"1,369,284","1,296,572","72,712",...,"1,304,141","1,224,398","79,743",6.1,"1,330,099","1,260,615","69,484",5.2,"$42,046",100.0
193,6000,CA,California,,,,,"17,893,080","16,931,590","961,490",...,"18,827,925","17,418,042","1,409,883",7.5,"18,981,770","17,798,614","1,183,156",6.2,"$64,483",100.0
252,8000,CO,Colorado,,,,,"2,664,677","2,565,218","99,459",...,"2,815,200","2,674,635","140,565",5.0,"2,828,529","2,718,698","109,831",3.9,"$63,945",100.0
317,9000,CT,Connecticut,,,,,"1,856,209","1,773,159","83,050",...,"1,886,398","1,761,610","124,788",6.6,"1,888,001","1,781,517","106,484",5.6,"$71,333",100.0
326,10000,DE,Delaware,,,,,"443,573","428,312","15,261",...,"453,631","427,708","25,923",5.7,"467,472","444,578","22,894",4.9,"$61,327",100.0
330,11000,DC,District of Columbia,,,,,"322,237","304,426","17,811",...,"378,082","348,729","29,353",7.8,"388,388","361,544","26,844",6.9,"$73,115",100.0
332,12000,FL,Florida,,,,,"9,157,124","8,789,770","367,354",...,"9,606,715","8,999,446","607,269",6.3,"9,675,328","9,153,264","522,064",5.4,"$49,416",100.0
400,13000,GA,Georgia,,,,,"4,815,818","4,597,640","218,178",...,"4,753,765","4,416,715","337,050",7.1,"4,770,873","4,490,931","279,942",5.9,"$51,225",100.0
560,15000,HI,Hawaii,,,,,"638,395","620,535","17,860",...,"668,346","639,148","29,198",4.4,"677,439","652,939","24,500",3.6,"$73,097",100.0
565,16000,ID,Idaho,,,,,"754,438","731,235","23,203",...,"781,390","743,574","37,816",4.8,"797,475","764,463","33,012",4.1,"$48,311",100.0
610,17000,IL,Illinois,,,,,"6,665,601","6,334,010","331,591",...,"6,515,198","6,053,884","461,314",7.1,"6,512,386","6,126,307","386,079",5.9,"$59,590",100.0
713,18000,IN,Indiana,,,,,"3,207,687","3,061,042","146,645",...,"3,227,970","3,035,984","191,986",5.9,"3,265,761","3,109,217","156,544",4.8,"$50,510",100.0
806,19000,IA,Iowa,,,,,"1,660,677","1,599,332","61,345",...,"1,697,712","1,626,270","71,442",4.2,"1,701,329","1,638,868","62,461",3.7,"$54,843",100.0
906,20000,KS,Kansas,,,,,"1,483,458","1,420,449","63,009",...,"1,494,188","1,425,970","68,218",4.6,"1,499,009","1,435,884","63,125",4.2,"$53,802",100.0
1012,21000,KY,Kentucky,,,,,"2,032,082","1,922,220","109,862",...,"2,005,603","1,875,932","129,671",6.5,"1,953,393","1,847,938","105,455",5.4,"$45,178",100.0
1133,22000,LA,Louisiana,,,,,"2,030,434","1,944,038","86,396",...,"2,156,737","2,018,593","138,144",6.4,"2,160,195","2,025,102","135,093",6.3,"$45,829",100.0
1198,23000,ME,Maine,,,,,"700,468","667,781","32,687",...,"696,578","657,302","39,276",5.6,"679,756","649,855","29,901",4.4,"$51,419",100.0
1215,24000,MD,Maryland,,,,,"2,970,094","2,867,348","102,746",...,"3,128,296","2,946,520","181,776",5.8,"3,151,929","2,988,101","163,828",5.2,"$75,784",100.0
1240,25000,MA,Massachusetts,,,,,"3,426,009","3,268,096","157,913",...,"3,557,362","3,353,138","204,224",5.7,"3,569,956","3,392,107","177,849",5.0,"$70,659",100.0
1255,26000,MI,Michigan,,,,,"5,011,120","4,658,939","352,181",...,"4,754,282","4,408,144","346,138",7.3,"4,750,627","4,492,989","257,638",5.4,"$51,063",100.0
1339,27000,MN,Minnesota,,,,,"2,906,390","2,773,704","132,686",...,"2,982,750","2,858,592","124,158",4.2,"3,010,367","2,898,864","111,503",3.7,"$63,459",100.0
1427,28000,MS,Mississippi,,,,,"1,303,514","1,224,059","79,455",...,"1,249,288","1,154,812","94,476",7.6,"1,272,657","1,189,646","83,011",6.5,"$40,630",100.0
1510,29000,MO,Missouri,,,,,"3,034,579","2,879,647","154,932",...,"3,051,812","2,863,982","187,830",6.2,"3,113,760","2,958,176","155,584",5.0,"$50,200",100.0
1626,30000,MT,Montana,,,,,"502,070","484,189","17,881",...,"515,947","491,938","24,009",4.7,"522,727","501,186","21,541",4.1,"$49,650",100.0
1683,31000,NE,Nebraska,,,,,"978,763","949,494","29,269",...,"1,013,899","980,833","33,066",3.3,"1,012,973","982,707","30,266",3.0,"$55,073",100.0
1777,32000,NV,Nevada,,,,,"1,330,396","1,270,572","59,824",...,"1,401,801","1,291,040","110,761",7.9,"1,425,711","1,329,552","96,159",6.7,"$52,544",100.0
1795,33000,NH,New Hampshire,,,,,"737,942","712,008","25,934",...,"740,609","708,896","31,713",4.3,"741,192","715,727","25,465",3.4,"$70,003",100.0
1806,34000,NJ,New Jersey,,,,,"4,441,797","4,251,815","189,982",...,"4,513,600","4,209,699","303,901",6.7,"4,543,777","4,288,825","254,952",5.6,"$72,337",100.0
1828,35000,NM,New Mexico,,,,,"934,027","898,998","35,029",...,"921,380","859,305","62,075",6.7,"919,889","859,242","60,647",6.6,"$45,524",100.0
1862,36000,NY,New York,,,,,"9,522,056","9,088,207","433,849",...,"9,595,304","8,989,429","605,875",6.3,"9,679,321","9,166,246","513,075",5.3,"$60,805",100.0
1925,37000,NC,North Carolina,,,,,"4,512,856","4,300,304","212,552",...,"4,690,562","4,396,286","294,276",6.3,"4,769,245","4,495,473","273,772",5.7,"$47,884",100.0
2026,38000,ND,North Dakota,,,,,"367,234","355,766","11,468",...,"415,286","404,147","11,139",2.7,"414,344","403,058","11,286",2.7,"$61,674",100.0
2080,39000,OH,Ohio,,,,,"5,990,292","5,657,718","332,574",...,"5,702,698","5,372,754","329,944",5.8,"5,700,344","5,423,019","277,325",4.9,"$51,086",100.0
2169,40000,OK,Oklahoma,,,,,"1,726,259","1,655,490","70,769",...,"1,797,934","1,717,136","80,798",4.5,"1,842,049","1,763,844","78,205",4.2,"$48,595",100.0
2247,41000,OR,Oregon,,,,,"1,921,766","1,822,772","98,994",...,"1,939,396","1,807,328","132,068",6.8,"1,969,466","1,857,114","112,352",5.7,"$54,074",100.0
2284,42000,PA,Pennsylvania,,,,,"6,342,997","6,064,063","278,934",...,"6,391,421","6,015,668","375,753",5.9,"6,423,903","6,093,858","330,045",5.1,"$55,683",100.0
2352,44000,RI,Rhode Island,,,,,"573,173","543,401","29,772",...,"555,955","513,217","42,738",7.7,"554,558","521,434","33,124",6.0,"$57,265",100.0
2358,45000,SC,South Carolina,,,,,"2,125,891","2,005,686","120,205",...,"2,216,782","2,074,277","142,505",6.4,"2,257,077","2,122,573","134,504",6.0,"$47,308",100.0
2405,46000,SD,South Dakota,,,,,"442,499","430,011","12,488",...,"448,631","433,203","15,428",3.4,"452,300","438,077","14,223",3.1,"$53,263",100.0
2472,47000,TN,Tennessee,,,,,"3,063,669","2,920,352","143,317",...,"3,046,632","2,847,777","198,855",6.5,"3,062,775","2,886,024","176,751",5.8,"$47,243",100.0
2568,48000,TX,Texas,,,,,"11,431,631","10,941,413","490,218",...,"13,022,851","12,358,703","664,148",5.1,"13,078,304","12,494,350","583,954",4.5,"$55,668",100.0
2823,49000,UT,Utah,,,,,"1,359,129","1,324,060","35,069",...,"1,431,553","1,377,013","54,540",3.8,"1,464,404","1,412,473","51,931",3.5,"$62,961",100.0
2853,50000,VT,Vermont,,,,,"353,739","339,547","14,192",...,"347,898","334,044","13,854",4.0,"344,414","331,824","12,590",3.7,"$56,883",100.0
2868,51000,VA,Virginia,,,,,"4,036,835","3,914,087","122,748",...,"4,257,986","4,036,280","221,706",5.2,"4,240,470","4,051,908","188,562",4.4,"$66,263",100.0
3002,53000,WA,Washington,,,,,"3,403,163","3,243,308","159,855",...,"3,492,866","3,278,975","213,891",6.1,"3,544,242","3,343,992","200,250",5.7,"$64,080",100.0
3042,54000,WV,West Virginia,,,,,"811,160","773,990","37,170",...,"789,850","737,479","52,371",6.6,"785,049","732,146","52,903",6.7,"$41,969",100.0
3098,55000,WI,Wisconsin,,,,,"3,087,828","2,936,452","151,376",...,"3,086,365","2,918,966","167,399",5.4,"3,095,376","2,952,797","142,579",4.6,"$55,623",100.0
3171,56000,WY,Wyoming,,,,,"286,560","278,486","8,074",...,"306,933","294,207","12,726",4.1,"306,012","293,262","12,750",4.2,"$61,213",100.0
3195,72000,PR,Puerto Rico,,,,,"1,387,359","1,232,266","155,093",...,"1,138,984","981,100","157,884",13.9,"1,131,005","994,942","136,063",12.0,,

In [42]:
# It's crude, but let's just forcibly it.
states = states.loc[df['FIPStxt'] != 72000]

In [43]:
# Including headers, this should be 51.
len(states)

51

In [46]:
states

,FIPStxt,State,Area_name,Rural_urban_continuum_code_2003,Urban_influence_code_2003,Rural_urban_continuum_code_2013,Urban_influence_code_2013,Civilian_labor_force_2007,Employed_2007,Unemployed_2007,...,Civilian_labor_force_2014,Employed_2014,Unemployed_2014,Unemployment_rate_2014,Civilian_labor_force_2015,Employed_2015,Unemployed_2015,Unemployment_rate_2015,Median_Household_Income_2015,Med_HH_Income_Percent_of_State_Total_2015
0,1000,AL,Alabama,,,,,"2,175,612","2,089,127","86,485",...,"2,161,313","2,014,284","147,029",6.8,"2,146,157","2,015,189","130,968",6.1,"$44,833",100.0
68,2000,AK,Alaska,,,,,"350,785","328,579","22,206",...,"365,890","340,804","25,086",6.9,"363,822","340,227","23,595",6.5,"$73,391",100.0
101,4000,AZ,Arizona,,,,,"3,034,016","2,917,117","116,899",...,"3,097,112","2,886,412","210,700",6.8,"3,152,708","2,959,518","193,190",6.1,"$51,473",100.0
117,5000,AR,Arkansas,,,,,"1,369,284","1,296,572","72,712",...,"1,304,141","1,224,398","79,743",6.1,"1,330,099","1,260,615","69,484",5.2,"$42,046",100.0
193,6000,CA,California,,,,,"17,893,080","16,931,590","961,490",...,"18,827,925","17,418,042","1,409,883",7.5,"18,981,770","17,798,614","1,183,156",6.2,"$64,483",100.0
252,8000,CO,Colorado,,,,,"2,664,677","2,565,218","99,459",...,"2,815,200","2,674,635","140,565",5.0,"2,828,529","2,718,698","109,831",3.9,"$63,945",100.0
317,9000,CT,Connecticut,,,,,"1,856,209","1,773,159","83,050",...,"1,886,398","1,761,610","124,788",6.6,"1,888,001","1,781,517","106,484",5.6,"$71,333",100.0
326,10000,DE,Delaware,,,,,"443,573","428,312","15,261",...,"453,631","427,708","25,923",5.7,"467,472","444,578","22,894",4.9,"$61,327",100.0
330,11000,DC,District of Columbia,,,,,"322,237","304,426","17,811",...,"378,082","348,729","29,353",7.8,"388,388","361,544","26,844",6.9,"$73,115",100.0
332,12000,FL,Florida,,,,,"9,157,124","8,789,770","367,354",...,"9,606,715","8,999,446","607,269",6.3,"9,675,328","9,153,264","522,064",5.4,"$49,416",100.0
400,13000,GA,Georgia,,,,,"4,815,818","4,597,640","218,178",...,"4,753,765","4,416,715","337,050",7.1,"4,770,873","4,490,931","279,942",5.9,"$51,225",100.0
560,15000,HI,Hawaii,,,,,"638,395","620,535","17,860",...,"668,346","639,148","29,198",4.4,"677,439","652,939","24,500",3.6,"$73,097",100.0
565,16000,ID,Idaho,,,,,"754,438","731,235","23,203",...,"781,390","743,574","37,816",4.8,"797,475","764,463","33,012",4.1,"$48,311",100.0
610,17000,IL,Illinois,,,,,"6,665,601","6,334,010","331,591",...,"6,515,198","6,053,884","461,314",7.1,"6,512,386","6,126,307","386,079",5.9,"$59,590",100.0
713,18000,IN,Indiana,,,,,"3,207,687","3,061,042","146,645",...,"3,227,970","3,035,984","191,986",5.9,"3,265,761","3,109,217","156,544",4.8,"$50,510",100.0
806,19000,IA,Iowa,,,,,"1,660,677","1,599,332","61,345",...,"1,697,712","1,626,270","71,442",4.2,"1,701,329","1,638,868","62,461",3.7,"$54,843",100.0
906,20000,KS,Kansas,,,,,"1,483,458","1,420,449","63,009",...,"1,494,188","1,425,970","68,218",4.6,"1,499,009","1,435,884","63,125",4.2,"$53,802",100.0
1012,21000,KY,Kentucky,,,,,"2,032,082","1,922,220","109,862",...,"2,005,603","1,875,932","129,671",6.5,"1,953,393","1,847,938","105,455",5.4,"$45,178",100.0
1133,22000,LA,Louisiana,,,,,"2,030,434","1,944,038","86,396",...,"2,156,737","2,018,593","138,144",6.4,"2,160,195","2,025,102","135,093",6.3,"$45,829",100.0
1198,23000,ME,Maine,,,,,"700,468","667,781","32,687",...,"696,578","657,302","39,276",5.6,"679,756","649,855","29,901",4.4,"$51,419",100.0
1215,24000,MD,Maryland,,,,,"2,970,094","2,867,348","102,746",...,"3,128,296","2,946,520","181,776",5.8,"3,151,929","2,988,101","163,828",5.2,"$75,784",100.0
1240,25000,MA,Massachusetts,,,,,"3,426,009","3,268,096","157,913",...,"3,557,362","3,353,138","204,224",5.7,"3,569,956","3,392,107","177,849",5.0,"$70,659",100.0
1255,26000,MI,Michigan,,,,,"5,011,120","4,658,939","352,181",...,"4,754,282","4,408,144","346,138",7.3,"4,750,627","4,492,989","257,638",5.4,"$51,063",100.0
1339,27000,MN,Minnesota,,,,,"2,906,390","2,773,704","132,686",...,"2,982,750","2,858,592","124,158",4.2,"3,010,367","2,898,864","111,503",3.7,"$63,459",100.0
1427,28000,MS,Mississippi,,,,,"1,303,514","1,224,059","79,455",...,"1,249,288","1,154,812","94,476",7.6,"1,272,657","1,189,646","83,011",6.5,"$40,630",100.0
1510,29000,MO,Missouri,,,,,"3,034,579","2,879,647","154,932",...,"3,051,812","2,863,982","187,830",6.2,"3,113,760","2,958,176","155,584",5.0,"$50,200",100.0
1626,30000,MT,Montana,,,,,"502,070","484,189","17,881",...,"515,947","491,938","24,009",4.7,"522,727","501,186","21,541",4.1,"$49,650",100.0
1683,31000,NE,Nebraska,,,,,"978,763","949,494","29,269",...,"1,013,899","980,833","33,066",3.3,"1,012,973","982,707","30,266",3.0,"$55,073",100.0
1777,32000,NV,Nevada,,,,,"1,330,396","1,270,572","59,824",...,"1,401,801","1,291,040","110,761",7.9,"1,425,711","1,329,552","96,159",6.7,"$52,544",100.0
1795,33000,NH,New Hampshire,,,,,"737,942","712,008","25,934",...,"740,609","708,896","31,713",4.3,"741,192","715,727","25,465",3.4,"$70,003",100.0
1806,34000,NJ,New Jersey,,,,,"4,441,797","4,251,815","189,982",...,"4,513,600","4,209,699","303,901",6.7,"4,543,777","4,288,825","254,952",5.6,"$72,337",100.0
1828,35000,NM,New Mexico,,,,,"934,027","898,998","35,029",...,"921,380","859,305","62,075",6.7,"919,889","859,242","60,647",6.6,"$45,524",100.0
1862,36000,NY,New York,,,,,"9,522,056","9,088,207","433,849",...,"9,595,304","8,989,429","605,875",6.3,"9,679,321","9,166,246","513,075",5.3,"$60,805",100.0
1925,37000,NC,North Carolina,,,,,"4,512,856","4,300,304","212,552",...,"4,690,562","4,396,286","294,276",6.3,"4,769,245","4,495,473","273,772",5.7,"$47,884",100.0
2026,38000,ND,North Dakota,,,,,"367,234","355,766","11,468",...,"415,286","404,147","11,139",2.7,"414,344","403,058","11,286",2.7,"$61,674",100.0
2080,39000,OH,Ohio,,,,,"5,990,292","5,657,718","332,574",...,"5,702,698","5,372,754","329,944",5.8,"5,700,344","5,423,019","277,325",4.9,"$51,086",100.0
2169,40000,OK,Oklahoma,,,,,"1,726,259","1,655,490","70,769",...,"1,797,934","1,717,136","80,798",4.5,"1,842,049","1,763,844","78,205",4.2,"$48,595",100.0
2247,41000,OR,Oregon,,,,,"1,921,766","1,822,772","98,994",...,"1,939,396","1,807,328","132,068",6.8,"1,969,466","1,857,114","112,352",5.7,"$54,074",100.0
2284,42000,PA,Pennsylvania,,,,,"6,342,997","6,064,063","278,934",...,"6,391,421","6,015,668","375,753",5.9,"6,423,903","6,093,858","330,045",5.1,"$55,683",100.0
2352,44000,RI,Rhode Island,,,,,"573,173","543,401","29,772",...,"555,955","513,217","42,738",7.7,"554,558","521,434","33,124",6.0,"$57,265",100.0
2358,45000,SC,South Carolina,,,,,"2,125,891","2,005,686","120,205",...,"2,216,782","2,074,277","142,505",6.4,"2,257,077","2,122,573","134,504",6.0,"$47,308",100.0
2405,46000,SD,South Dakota,,,,,"442,499","430,011","12,488",...,"448,631","433,203","15,428",3.4,"452,300","438,077","14,223",3.1,"$53,263",100.0
2472,47000,TN,Tennessee,,,,,"3,063,669","2,920,352","143,317",...,"3,046,632","2,847,777","198,855",6.5,"3,062,775","2,886,024","176,751",5.8,"$47,243",100.0
2568,48000,TX,Texas,,,,,"11,431,631","10,941,413","490,218",...,"13,022,851","12,358,703","664,148",5.1,"13,078,304","12,494,350","583,954",4.5,"$55,668",100.0
2823,49000,UT,Utah,,,,,"1,359,129","1,324,060","35,069",...,"1,431,553","1,377,013","54,540",3.8,"1,464,404","1,412,473","51,931",3.5,"$62,961",100.0
2853,50000,VT,Vermont,,,,,"353,739","339,547","14,192",...,"347,898","334,044","13,854",4.0,"344,414","331,824","12,590",3.7,"$56,883",100.0
2868,51000,VA,Virginia,,,,,"4,036,835","3,914,087","122,748",...,"4,257,986","4,036,280","221,706",5.2,"4,240,470","4,051,908","188,562",4.4,"$66,263",100.0
3002,53000,WA,Washington,,,,,"3,403,163","3,243,308","159,855",...,"3,492,866","3,278,975","213,891",6.1,"3,544,242","3,343,992","200,250",5.7,"$64,080",100.0
3042,54000,WV,West Virginia,,,,,"811,160","773,990","37,170",...,"789,850","737,479","52,371",6.6,"785,049","732,146","52,903",6.7,"$41,969",100.0
3098,55000,WI,Wisconsin,,,,,"3,087,828","2,936,452","151,376",...,"3,086,365","2,918,966","167,399",5.4,"3,095,376","2,952,797","142,579",4.6,"$55,623",100.0
3171,56000,WY,Wyoming,,,,,"286,560","278,486","8,074",...,"306,933","294,207","12,726",4.1,"306,012","293,262","12,750",4.2,"$61,213",100.0

In [47]:
states.to_csv("states_unemployment.csv")